### ISSUE TITLE
vi mode indicator missing

### ISSUE THREAD

**Issue by sonnius** [mgee/slimline#17]
I've been using slimline for a while now and I feel the only piece that's missing for me is a vi modal indicator.

Could such a feature be added to the roadmap?

Thanks,
Sonnius

**Comment by mengelbrecht** [comment]
I added a `vi_mode` section in the develop branch. It is active by default and its format can be customized.

**Comment by sonnius** [comment]
mgee, that looks like the exact thing I wanted!

Switched to develop for now, will report bugs if I find them.

Thanks!

Sonnius
