### ISSUE TITLE
Changing vi mode prints new prompt line.

### ISSUE THREAD

**Issue by ghost** [mgee/slimline#19]
Hi there,

I have noticed that my prompt gets printed couple of times (three) on all newly opened terminal windows.

I have pinned it down to `zle reset-prompt` command, which I call once from my zsh configuration and slimline does once too.

My code to put vi-mode indicator nicely in prompt rather than as separate section:

```
function zle-line-init-vimode zle-keymap-select {
  psvar[1]="${${KEYMAP/vicmd/❮}/(main|viins)/❯}"
  zle .reset-prompt
}

zle -N zle-keymap-select

# Enables terminal application mode and updates editor information
function zle-line-init {
  zle-line-init-vimode
  (( $+terminfo[smkx] )) && echoti smkx
}

zle -N zle-line-init

# Disables terminal application mode and updates editor information
function zle-line-finish {
  (( $+terminfo[rmkx] )) && echoti rmkx
}
zle -N zle-line-finish
```
slimline calls `prompt-reset` here https://github.com/mgee/slimline/blob/master/slimline.zsh#L32

It also reprints prompt when I change between insert and command modes.

What is interesting is that it does not do that when there is text printed above prompt (and since I use `zsh -i` as login shell to get rid of `Last Login: <date>` output) there is no text above prompt when opening new terminal window. Please note that touching ~/.hushlogin and removing -i from zsh invocation also causes multiple prompts line. Removing `-i` from zsh invocation does sole the problem, but is not ideal.

Can you think of any way around my problem? Thanks.

**Comment by mengelbrecht** [comment]
Maybe this is caused by the interaction with the `vi_mode` section.
Please try and disable the `vi_mode` section by removing it from the right prompt using this setting:
```shell
export SLIMLINE_RIGHT_PROMPT_SECTIONS="execution_time exit_status git aws_profile virtualenv nodejs"
```

**Comment by ghost** [comment]
Don't have it there already. Using:

    ~ ❯ echo $SLIMLINE_RIGHT_PROMPT_SECTIONS
    execution_time exit_status git virtualenv aws_profile

**Comment by mengelbrecht** [comment]
I tried to reproduce the issue but the prompt is showing normally for me (macOS, zsh: 5.3). I currently have no idea how to debug the issue or workaround it other than the way you already found :-/.

**Comment by ghost** [comment]
This is odd, I created test environment with extremely simplistic zshrc:

    source ~/.local/share/zsh/bundle/mafredri/zsh-async/async.zsh
    source ~/.local/share/zsh/bundle/mgee/slimline/slimline.zsh

and with homebrewed zsh and iTerm2 startup command set to `/usr/local/bin/zsh -i` I get four empty lines when starting new terminal - please note that I have to scroll up to see those empty prompt lines.

This is what it looks like: 
<img width="85" alt="screenshot 2018-10-28 at 10 55 39" src="https://user-images.githubusercontent.com/796021/47614439-2f6b8c00-daa0-11e8-9236-dc7d34643e44.png">

**Comment by mengelbrecht** [comment]
This is odd. It happens for me too. However, only when starting a new iTerm2 window. 
Inside a terminal `exec /usr/local/bin/zsh -i` does not trigger this behaviour.
It seems that the reset-prompt command https://github.com/mengelbrecht/slimline/blob/32a279e772577966717f44c09fb2ec90ad5f0fe4/slimline.zsh#L32 does not redraw the prompt on the current line but on the next line instead 🧐

The same test in Terminal.app does not show the empty prompt lines. @katsika does the issue also occur in Terminal.app for you?

**Comment by ghost** [comment]
Correct, couldn't make the issue appear on Terminal.app.

**Comment by mengelbrecht** [comment]
I opened an issue about this in the iTerm gitlab repository: https://gitlab.com/gnachman/iterm2/issues/7454

The issue seems to be caused by an iTerm workaround for tmux. To prevent the multiple new prompt lines you have to emit a line before the first prompt (e.g. via an echo in the zshrc or by using the default `Last Login: <date>` message from zsh).
