### ISSUE TITLE
async_job:zpty:12: no such pty command: prompt_slimline

### ISSUE THREAD

**Issue by peti** [mgee/slimline#20]
I regularly start seeing the error message

    async_job:zpty:12: no such pty command: prompt_slimline

after working in my shell for a while. The slimline theme works fine, but then it suddenly malfunctions in that way. I have no clue why.

I seem to be able to reproduce that issue more regularly if I set

    SLIMLINE_ENABLE_ASYNC_AUTOLOAD=0

and install `async` explicitly via

    zplug "mafredri/zsh-async", from:"github", use:"async.zsh"

*before* I initialize slimline. But it happens with autoloading enabled, too, only less frequently. Can you make any sense of this?

**Comment by mengelbrecht** [comment]
This is the first time I see this error. It occurs if the async worker used by slimline is stopped somehow.

I read up on the zsh-async code and I assume this can happen if file descriptor for the zle watcher is broken and zsh-async stops the watcher. The next time the prompt is rendered slimline tries to use the stopped worker and you get the error message you posted.

I added some code (0af57cad2e9dff94bd0a4578f9bf02e474a4bd5a) to the async handling which catches this and restarts the worker.
Additionally it emits the error message from zsh-async like this:
```Error from async worker: <some-error-message>```

Please try the latest code from the master branch and see if it improves your situation and if you encounter the error message.

**Comment by peti** [comment]
The first impression is pretty good! I updated my copy of slimline yesterday and did not see another one of those errors yet again. I'll keep you posted what happens after a little more time.

I *did* see the following new error, though:

    Error from async worker: prompt_slimline:zle -F 16 returned error hup

This was harmless, i.e. zsh showed it once but still worked just fine afterwards. Just FYI.

**Comment by mengelbrecht** [comment]
The error you saw would have lead to `async_job:zpty:12: no such pty command: prompt_slimline` before I made the changes.
If the error occurred more than once, did you notice any similarities when it occurred (for example always in the same directory etc.)?

**Comment by peti** [comment]
> If the error occurred more than once, did you notice any similarities when it occurred (for example always in the same directory etc.)?

I have seen that error a couple of times now. I couldn't say that I noticed and rules or regularities about it. It happened in all kinds of directories, as `root, as a normal user, etc. The good news is, though, that the original issue hasn't occurred since (and this error appears to be harmless).

**Comment by mengelbrecht** [comment]
I removed the error output in ed847174efa111b24b6737389129504b966dbb14 because the prompt recovers automatically now.
It seems that the zle file descriptor can break sometimes according to https://github.com/mafredri/zsh-async/pull/31.

I am closing this issue because the prompt handles this case now.

**Comment by peti** [comment]
Alright! Thank you very much for the quick fix.
