### ISSUE TITLE
Newline section?

### ISSUE THREAD

**Issue by ftpd** [mgee/slimline#22]
Hi.
This is more like feature request.
I like simplicity and clean look of slimline, but I'm not so used to have right prompt. The problem is, after putting everything I (we?) need to left prompt, it ends in like 3/4 of terminal space ;-)

So I was wondering, is it possible to add section that will simply create newline? I've tried with simple:
`slimline::section::newline::render() {
  printf "\n"
}`
but it doesn't work :(

**Comment by mengelbrecht** [comment]
Hi there. Interesting use case :-)

It worked for me using the following newline section:
```shell
slimline::section::newline::render() {
    echo "\\\n"
}
```

Does the code above also work for you?

**Comment by ftpd** [comment]
Thanks for fast reply.
It works... almost. After typing some command (simple one, like ls or so) I'm getting proper output and in a short moment, when slimline prompt is drawn, the last line of this output disappear. Sometimes (but very rarely, like ~10% times) it's ok.

**Comment by mengelbrecht** [comment]
I added the newline section in aa72218917706d6085f7e5140eaca7ebda21a0e6.
However, I could not reproduce the issue you are seeing :-/

**Comment by ftpd** [comment]
Thanks for this commit!
I've identified the issue cause, it's one of my custom section file. I'll open new issue for that, as it's irrelevant do this matter.
