### ISSUE TITLE
Custom script for k8s namespace breaks everything.

### ISSUE THREAD

**Issue by ftpd** [mgee/slimline#23]
Disclaimer: I know that this github's section is not a support line, so no hard feelings if you decide to close this - but every help would be appreciated ;-)

------

So, I have those two simple scripts:
`slimline::section::k8s_context::precmd() {
  unset slimline_section_k8s_context_output
}

slimline::section::k8s_context::async_task() {
  kubectl config current-context
}

slimline::section::k8s_context::async_task_complete() {
  slimline_section_k8s_context_output=$2
}

slimline::section::k8s_context::render() {
  [[ -z "${slimline_section_k8s_context_output}" ]] && return

  slimline::utils::expand "k8s_context" "%F{blue}\U2388 |output|%f" \
    "output" "${slimline_section_k8s_context_output}"
}`

and

`slimline::section::k8s_namespace::precmd() {
  unset slimline_section_k8s_namespace_output
}

slimline::section::k8s_namespace::async_task() {
  kubectl config view --minify --output 'jsonpath={..namespace}'
}

slimline::section::k8s_namespace::async_task_complete() {
  slimline_section_k8s_namespace_output=$2
}

slimline::section::k8s_namespace::render() {
  [[ -z "${slimline_section_k8s_namespace_output}" ]] && return

  slimline::utils::expand "k8s_namespace" "ns:%F{blue}|output|%f" \
    "output" "${slimline_section_k8s_namespace_output}"
}`

The first one works good, but when I use the second one, my display goes crazy - after every command, it's output is there properly, but after a very short moment (less than a second) the last line of output is deleted, and in it's place there is my slimline prompt. What am I doing wrong here? I've tried to put everything in one section, but I don't know, how ;-)

**Comment by mengelbrecht** [comment]
This seems to be caused when the newline section is rendered and zle tries to redraw the prompt. When the last character is a newline zle moves up one line and overwrites it. 

Can you try the `bugfix/multiline-prompt` branch if it fixes the issue?

**Comment by ftpd** [comment]
Yes, now everything works.
