### ISSUE TITLE
Support request: Problem with urbainvaes/fzf-marks

### ISSUE THREAD

**Issue by ghost** [mgee/slimline#9]
Hey,

I have set up slightly modified version of [urbainvaes/fzf-marks](/urbainvaes/fzf-marks). Problem I have is after using FZF to change into directory gitline part of slimline does not get refreshed. So, if I am arriving from another git repository I am still presented information for old repository until I execute any command. It also happens when I arrive from non git repository directory, in which case I don't get gitline part at all.

Is there anything you can see that might be causing gitline not to be async'ed upon `cd` invoked in [this line](https://github.com/urbainvaes/fzf-marks/blob/master/fzf-marks.plugin.zsh#L24)?
Thanks!

**Comment by mengelbrecht** [comment]
This should be fixed on the [next branch](/mgee/slimline/tree/next).

**Comment by ghost** [comment]
It works, thank you!
